from agno.agent import Agent, RunResponse
from agno.models.anthropic import Claude
from agno.models.ollama import Ollama

task = "9.11 and 9.9 -- which is bigger?"


def reasoning(prompt: str) -> str:
    """Reason over the given prompt and return the response.

    Args:
        prompt: The prompt to reason over
    Returns:
        The response generated by the reasoning model
    """
    reasoning_agent = Agent(
        model=Ollama(id="deepseek-r1:32b"),
        instructions=["Provide detailed reasoning steps for the given prompt."],
    )
    response: RunResponse = reasoning_agent.run(prompt)

    return response.content


agent = Agent(
    model=Claude(id="claude-3-5-sonnet-20241022"),
    context={"reasoning": reasoning(task)},
    context_type="reasoning",
    add_context=True,
)
agent.print_response(task, stream=True)
