from agno.agent import Agent
from agno.models.openai import OpenAIChat
from agno.tools.exa import ExaTools
from agno.tools.dalle import DalleTools
from agno.tools.browserless import BrowserlessTools

# Competitor Intelligence Agent: Analyzes competitors and market trends
competitor_intelligence_agent = Agent(
    name="competitor_intelligence_agent",
    model=OpenAIChat(id="gpt-4o-mini"),
    tools=[BrowserlessTools(), ExaTools()],
    role="""You are a market intelligence agent tasked with analyzing a list of competitors.
Examine competitor strategies and market trends to provide detailed insights.
Your research will inform and support the creative copy and visual asset generation for a social media post.
""",
    markdown=True,
    show_tool_calls=True,
)

# Creative Copy Agent: Crafts engaging posts based on market and competitor insights
creative_copy_agent = Agent(
    name="creative_copy_agent",
    model=OpenAIChat(id="o3-mini"),
    tools=[ExaTools()],
    role="""You are a creative copy strategist. Based on the market and competitor insights provided,
create a compelling social media post that engages the target audience and highlights unique value propositions.
""",
    markdown=True,
    show_tool_calls=True,
)

# Visual Asset Agent: Generates image concepts using market research and competitor analysis
better_image_generator_agent = Agent(
    name="better_image_generator_agent",
    model=OpenAIChat(id="gpt-4o-mini"),
    tools=[DalleTools()],
    role="""You are a better image generator agent. Leverage market insights and competitor analysis to generate
a visually striking image that complements the social media post narrative.
""",
    markdown=True,
    show_tool_calls=True,
)

# Social Post Director: Integrates insights from all team members to direct the final content creation
social_post_director = Agent(
    name="social_post_director",
    model=OpenAIChat(id="gpt-4o-mini"),
    role="""You are the social media post director responsible for curating a cohesive and engaging post.
Coordinate the detailed analysis from the competitor intelligence agent, the creative input from the creative copy agent,
and the image generated by the better image generator agent to produce a unified post that drives audience engagement.
""",
    team=[competitor_intelligence_agent, creative_copy_agent, better_image_generator_agent],
    markdown=True,
    show_tool_calls=True,
)

social_post_director.print_response(
    "Our product is an AI-powered agent called agno.com. Please conduct market and competitor research to help us create an outstanding post."
)

